name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.7
        with:
          args: --exact-timestamps --delete public/ s3://YOUR_BUCKET_NAME/
        env:
          AWS_S3_BUCKET: daily-blog-by-rajababu
          AWS_REGION: US East (N. Virginia)
          AWS_ACCESS_KEY_ID: AKIAX6W6C2BLHBTJHJ7S
          AWS_SECRET_ACCESS_KEY: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
